server:
  port: 9090
 
spring:  mvc:    view:      prefix: /views/
      suffix: .jsp
    datasource:    driver-class-name: 
    url: jdbc:mysql://localhost:3306/ashokItJpa
    username: root
    password: root
    
messages:
  welcomeMsg: Welcome to Java's World
  greetMsg: Good Morning
  
myapp:  
  messages:
    welcomeMsg: Welcome to Java's World
    greetMsg: Good Morning
        
  
   